/* eslint-disable max-lines */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/conversations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List conversations
     * @description Get all conversations for the current user
     */
    get: operations["listConversations"];
    put?: never;
    /**
     * Create conversation
     * @description Create a new conversation
     */
    post: operations["createConversation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/conversations/{conversationId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get conversation
     * @description Get a single conversation by ID
     */
    get: operations["getConversation"];
    put?: never;
    post?: never;
    /**
     * Delete conversation
     * @description Delete a conversation
     */
    delete: operations["deleteConversation"];
    options?: never;
    head?: never;
    /**
     * Update conversation
     * @description Update a conversation
     */
    patch: operations["updateConversation"];
    trace?: never;
  };
  "/api/conversations/{conversationId}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List messages
     * @description Get messages for a conversation
     */
    get: operations["listMessages"];
    put?: never;
    /**
     * Send message
     * @description Send a message in a conversation
     */
    post: operations["sendMessage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/conversations/{conversationId}/messages/{messageId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete message
     * @description Delete a message
     */
    delete: operations["deleteMessage"];
    options?: never;
    head?: never;
    /**
     * Update message
     * @description Update a message
     */
    patch: operations["updateMessage"];
    trace?: never;
  };
  "/api/conversations/{conversationId}/messages/{messageId}/stream": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Stream message response
     * @description Stream AI response for a message using Server-Sent Events
     */
    get: operations["streamMessageResponse"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/customers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List customers
     * @description Get all customers
     */
    get: operations["listCustomers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/customers/{customerId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get customer
     * @description Get customer details
     */
    get: operations["getCustomer"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update customer
     * @description Update customer details
     */
    patch: operations["updateCustomer"];
    trace?: never;
  };
  "/api/customers/{customerId}/interactions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get customer interactions
     * @description Get all interactions for a customer
     */
    get: operations["getCustomerInteractions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/analytics/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get analytics overview
     * @description Get high-level analytics metrics
     */
    get: operations["getAnalyticsOverview"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/analytics/conversations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get conversation analytics
     * @description Get detailed conversation metrics
     */
    get: operations["getConversationAnalytics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/analytics/agents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get agent performance
     * @description Get agent performance metrics
     */
    get: operations["getAgentPerformance"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/agents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List agents
     * @description Get all configured AI agents
     */
    get: operations["listAgents"];
    put?: never;
    /**
     * Create agent
     * @description Create a new AI agent configuration
     */
    post: operations["createAgent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/agents/{agentId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get agent
     * @description Get agent details
     */
    get: operations["getAgent"];
    put?: never;
    post?: never;
    /**
     * Delete agent
     * @description Delete an agent
     */
    delete: operations["deleteAgent"];
    options?: never;
    head?: never;
    /**
     * Update agent
     * @description Update agent configuration
     */
    patch: operations["updateAgent"];
    trace?: never;
  };
  "/api/admin/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Check backend health status
     */
    get: operations["healthCheck"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/costs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get cost tracking
     * @description Get API usage and cost tracking
     */
    get: operations["getCostTracking"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/backend/switch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Switch backend
     * @description Switch between OpenAI and Anthropic backends
     */
    post: operations["switchBackend"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Conversation: {
      id: string;
      userId: string;
      title: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      metadata?: Record<string, never> | null;
    };
    ConversationList: {
      conversations: components["schemas"]["Conversation"][];
      total: number;
    };
    CreateConversationRequest: {
      title?: string;
      metadata?: Record<string, never> | null;
    };
    UpdateConversationRequest: {
      title?: string;
      metadata?: Record<string, never> | null;
    };
    Message: {
      id: string;
      conversationId: string;
      userId: string;
      /** @enum {string} */
      role: "USER" | "ASSISTANT" | "SYSTEM";
      content: string;
      metadata?: Record<string, never> | null;
      /** Format: date-time */
      createdAt: string;
    };
    MessageList: {
      messages: components["schemas"]["Message"][];
      nextCursor?: string | null;
      hasMore: boolean;
    };
    SendMessageRequest: {
      content: string;
      /** @enum {string} */
      role: "USER" | "ASSISTANT" | "SYSTEM";
      metadata?: Record<string, never> | null;
    };
    UpdateMessageRequest: {
      content: string;
    };
    Customer: {
      id: string;
      name: string;
      email: string;
      company?: string | null;
      phone?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      lastInteraction?: string | null;
      totalInteractions: number;
      metadata?: Record<string, never> | null;
    };
    CustomerList: {
      customers: components["schemas"]["Customer"][];
      total: number;
    };
    UpdateCustomerRequest: {
      name?: string;
      email?: string;
      company?: string | null;
      phone?: string | null;
      metadata?: Record<string, never> | null;
    };
    CustomerInteractions: {
      customerId: string;
      conversations: components["schemas"]["Conversation"][];
      totalInteractions: number;
      avgResponseTime: number;
      satisfactionScore?: number | null;
    };
    AnalyticsOverview: {
      totalConversations: number;
      totalMessages: number;
      totalCustomers: number;
      avgResponseTime: number;
      satisfactionScore: number;
      activeAgents: number;
      period: string;
    };
    ConversationAnalytics: {
      period: string;
      conversationsByDay: {
        date?: string;
        count?: number;
      }[];
      messagesByDay: {
        date?: string;
        count?: number;
      }[];
      avgMessagesPerConversation: number;
      avgConversationDuration: number;
    };
    AgentPerformance: {
      period: string;
      agents: {
        agentId?: string;
        agentName?: string;
        totalConversations?: number;
        totalMessages?: number;
        avgResponseTime?: number;
        satisfactionScore?: number;
        costUsd?: number;
      }[];
    };
    Agent: {
      id: string;
      name: string;
      description?: string | null;
      model: string;
      /** @enum {string} */
      provider: "openai" | "anthropic";
      systemPrompt?: string | null;
      temperature: number;
      maxTokens: number;
      isActive: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    AgentList: {
      agents: components["schemas"]["Agent"][];
    };
    CreateAgentRequest: {
      name: string;
      description?: string | null;
      model: string;
      /** @enum {string} */
      provider: "openai" | "anthropic";
      systemPrompt?: string | null;
      /** @default 0.7 */
      temperature: number;
      /** @default 2048 */
      maxTokens: number;
    };
    UpdateAgentRequest: {
      name?: string;
      description?: string | null;
      model?: string;
      systemPrompt?: string | null;
      temperature?: number;
      maxTokens?: number;
      isActive?: boolean;
    };
    HealthStatus: {
      /** @enum {string} */
      status: "healthy" | "degraded" | "unhealthy";
      /** Format: date-time */
      timestamp: string;
      version: string;
      database?: {
        status?: string;
        latency?: number;
      };
      aiProviders?: {
        openai?: {
          status?: string;
          latency?: number;
        };
        anthropic?: {
          status?: string;
          latency?: number;
        };
      };
    };
    CostTracking: {
      period: string;
      totalCostUsd: number;
      costByProvider: {
        openai?: number;
        anthropic?: number;
      };
      costByDay: {
        date?: string;
        cost?: number;
      }[];
      tokenUsage: {
        input?: number;
        output?: number;
        total?: number;
      };
    };
    SwitchBackendRequest: {
      /** @enum {string} */
      provider: "openai" | "anthropic";
      model?: string;
    };
    BackendStatus: {
      currentProvider: string;
      currentModel: string;
      /** Format: date-time */
      switchedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listConversations: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        status?: "active" | "archived" | "all";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of conversations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConversationList"];
        };
      };
    };
  };
  createConversation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateConversationRequest"];
      };
    };
    responses: {
      /** @description Conversation created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Conversation"];
        };
      };
    };
  };
  getConversation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Conversation details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Conversation"];
        };
      };
    };
  };
  deleteConversation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Conversation deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateConversation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateConversationRequest"];
      };
    };
    responses: {
      /** @description Conversation updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Conversation"];
        };
      };
    };
  };
  listMessages: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
      };
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of messages */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageList"];
        };
      };
    };
  };
  sendMessage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendMessageRequest"];
      };
    };
    responses: {
      /** @description Message sent */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Message"];
        };
      };
    };
  };
  deleteMessage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
        messageId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Message deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateMessage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
        messageId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMessageRequest"];
      };
    };
    responses: {
      /** @description Message updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Message"];
        };
      };
    };
  };
  streamMessageResponse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
        messageId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description SSE stream of message chunks */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": string;
        };
      };
    };
  };
  listCustomers: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of customers */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerList"];
        };
      };
    };
  };
  getCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customerId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Customer details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Customer"];
        };
      };
    };
  };
  updateCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customerId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCustomerRequest"];
      };
    };
    responses: {
      /** @description Customer updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Customer"];
        };
      };
    };
  };
  getCustomerInteractions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customerId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Customer interactions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerInteractions"];
        };
      };
    };
  };
  getAnalyticsOverview: {
    parameters: {
      query?: {
        period?: "24h" | "7d" | "30d" | "90d";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Analytics overview */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnalyticsOverview"];
        };
      };
    };
  };
  getConversationAnalytics: {
    parameters: {
      query?: {
        period?: "24h" | "7d" | "30d" | "90d";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Conversation analytics */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConversationAnalytics"];
        };
      };
    };
  };
  getAgentPerformance: {
    parameters: {
      query?: {
        period?: "24h" | "7d" | "30d" | "90d";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Agent performance metrics */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentPerformance"];
        };
      };
    };
  };
  listAgents: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of agents */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentList"];
        };
      };
    };
  };
  createAgent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAgentRequest"];
      };
    };
    responses: {
      /** @description Agent created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Agent"];
        };
      };
    };
  };
  getAgent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        agentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Agent details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Agent"];
        };
      };
    };
  };
  deleteAgent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        agentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Agent deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateAgent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        agentId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAgentRequest"];
      };
    };
    responses: {
      /** @description Agent updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Agent"];
        };
      };
    };
  };
  healthCheck: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Health status */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthStatus"];
        };
      };
    };
  };
  getCostTracking: {
    parameters: {
      query?: {
        period?: "24h" | "7d" | "30d" | "90d";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cost tracking data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CostTracking"];
        };
      };
    };
  };
  switchBackend: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SwitchBackendRequest"];
      };
    };
    responses: {
      /** @description Backend switched */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackendStatus"];
        };
      };
    };
  };
}
